users/config/routes.rb
Users::Application.routes.draw do
  resources :users

end

users/app/models/persona.rb
class Persona < ActiveRecord::Base
  self.table_name = "iuser_persona"
  self.primary_key = "id"
  #attr_accessible :id, :user_id, :assigned_usertype_id, :match_status
  belongs_to :user
end

users/app/models/user.rb
#class Email < ActiveRecord::Base
#  self.table_name =  "message_email"
#  self.primary_key = "id"

  #belongs_to :User,
  #  :foreign_key => 'user_id'

#  has_many :User,
#    :foreign_key => 'user_id',
#    :primary_key => 'id'
#end

class User < ActiveRecord::Base
  self.table_name = "iuser_user"
  self.primary_key = "id"
  
  has_many :personas, :foreign_key => "user_id"
end

#class Persona < ActiveRecord::Base
#  self.table_name = "iuser_persona"
#  self.primary_key = "id"
#  
#  #attr_accessible :id, :user_id, :assigned_usertype_id, :match_status
#  belongs_to :user 
#end

users/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

users/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: UsersDatatable.new(view_context)}

    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

   # respond_to do |format|
   #   format.html # show.html.erb
   #   format.json { render :json => @user }
   # end
  end
end

users/app/helpers/application_helper.rb
module ApplicationHelper
end

users/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">iMentor</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "About" %></li>
            <li><%= link_to "Contact Us" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<%= yield %>
</body>
</html>

users/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

users/app/views/users/index.html.erb
<h1>Listing users</h1>
    <table id="users" class="display table table-hover" data-source="<%= users_url(format: "json") %>">
      <thead>
      <tr>
        <th>Fname</th>
        <th>Lname</th>
        <th>Email</th>
      </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
<br />

users/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fname:</b>
  <%= @user.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @user.lname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>