last_email/config/routes.rb
LastEmail::Application.routes.draw do
  resources :blas

  resources :emails

end

last_email/app/models/bla.rb
class Bla < ActiveRecord::Base
  attr_accessible :content, :id, :sender_id,, :subject,
end

last_email/app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :content, :id, :sender_id,, :subject,
end

last_email/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

last_email/app/controllers/blas_controller.rb
class BlasController < ApplicationController
  # GET /blas
  # GET /blas.json
  def index
    @blas = Bla.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blas }
    end
  end

  # GET /blas/1
  # GET /blas/1.json
  def show
    @bla = Bla.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bla }
    end
  end

  # GET /blas/new
  # GET /blas/new.json
  def new
    @bla = Bla.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bla }
    end
  end

  # GET /blas/1/edit
  def edit
    @bla = Bla.find(params[:id])
  end

  # POST /blas
  # POST /blas.json
  def create
    @bla = Bla.new(params[:bla])

    respond_to do |format|
      if @bla.save
        format.html { redirect_to @bla, :notice => 'Bla was successfully created.' }
        format.json { render :json => @bla, :status => :created, :location => @bla }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bla.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blas/1
  # PUT /blas/1.json
  def update
    @bla = Bla.find(params[:id])

    respond_to do |format|
      if @bla.update_attributes(params[:bla])
        format.html { redirect_to @bla, :notice => 'Bla was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bla.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blas/1
  # DELETE /blas/1.json
  def destroy
    @bla = Bla.find(params[:id])
    @bla.destroy

    respond_to do |format|
      format.html { redirect_to blas_url }
      format.json { head :no_content }
    end
  end
end

last_email/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @emails }
    end
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
    @email = Email.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @email }
    end
  end

  # GET /emails/new
  # GET /emails/new.json
  def new
    @email = Email.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @email }
    end
  end

  # GET /emails/1/edit
  def edit
    @email = Email.find(params[:id])
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(params[:email])

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, :notice => 'Email was successfully created.' }
        format.json { render :json => @email, :status => :created, :location => @email }
      else
        format.html { render :action => "new" }
        format.json { render :json => @email.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /emails/1
  # PUT /emails/1.json
  def update
    @email = Email.find(params[:id])

    respond_to do |format|
      if @email.update_attributes(params[:email])
        format.html { redirect_to @email, :notice => 'Email was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @email.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email = Email.find(params[:id])
    @email.destroy

    respond_to do |format|
      format.html { redirect_to emails_url }
      format.json { head :no_content }
    end
  end
end

last_email/app/helpers/application_helper.rb
module ApplicationHelper
end

last_email/app/helpers/blas_helper.rb
module BlasHelper
end

last_email/app/helpers/emails_helper.rb
module EmailsHelper
end

last_email/app/views/blas/_form.html.erb
<%= form_for(@bla) do |f| %>
  <% if @bla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bla.errors.count, "error") %> prohibited this bla from being saved:</h2>

      <ul>
      <% @bla.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :sender_id, %><br />
    <%= f.text_field :sender_id, %>
  </div>
  <div class="field">
    <%= f.label :subject, %><br />
    <%= f.text_field :subject, %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

last_email/app/views/blas/edit.html.erb
<h1>Editing bla</h1>

<%= render 'form' %>

<%= link_to 'Show', @bla %> |
<%= link_to 'Back', blas_path %>

last_email/app/views/blas/index.html.erb
<h1>Listing blas</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Sender id,</th>
    <th>Subject,</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blas.each do |bla| %>
  <tr>
    <td><%= bla.id %></td>
    <td><%= bla.sender_id, %></td>
    <td><%= bla.subject, %></td>
    <td><%= bla.content %></td>
    <td><%= link_to 'Show', bla %></td>
    <td><%= link_to 'Edit', edit_bla_path(bla) %></td>
    <td><%= link_to 'Destroy', bla, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bla', new_bla_path %>

last_email/app/views/blas/new.html.erb
<h1>New bla</h1>

<%= render 'form' %>

<%= link_to 'Back', blas_path %>

last_email/app/views/blas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @bla.id %>
</p>

<p>
  <b>Sender id,:</b>
  <%= @bla.sender_id, %>
</p>

<p>
  <b>Subject,:</b>
  <%= @bla.subject, %>
</p>

<p>
  <b>Content:</b>
  <%= @bla.content %>
</p>


<%= link_to 'Edit', edit_bla_path(@bla) %> |
<%= link_to 'Back', blas_path %>

last_email/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LastEmail</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>